include(GetPrerequisites)

cmake_policy(SET CMP0057 NEW)

# Usage: cmake -D TARGET_FILE=<exe> -D TARGET_DIR=<dir> -D SEARCH_DIRS_FILE=<path> -P copy_deps.cmake
# Resolves with gp_resolve_item (so DLLs are found), but only copies if path is under SEARCH_DIRS (rejects Meld/PATH).

if(SEARCH_DIRS_FILE AND EXISTS "${SEARCH_DIRS_FILE}")
    file(READ "${SEARCH_DIRS_FILE}" SEARCH_DIRS)
endif()
string(STRIP "${SEARCH_DIRS}" SEARCH_DIRS)
string(REPLACE " " ";" SEARCH_DIRS "${SEARCH_DIRS}")
string(REPLACE "\n" ";" SEARCH_DIRS "${SEARCH_DIRS}")
list(REMOVE_DUPLICATES SEARCH_DIRS)

# True if path is under one of the search dirs (so we do not copy from Meld/PATH)
function(path_under_search_dirs path search_dirs_list out_var)
    get_filename_component(path_abs "${path}" REALPATH)
    string(REPLACE "\\" "/" path_abs "${path_abs}")
    set(inside FALSE)
    foreach(d IN LISTS search_dirs_list)
        get_filename_component(d_abs "${d}" REALPATH)
        string(REPLACE "\\" "/" d_abs "${d_abs}")
        string(FIND "${path_abs}" "${d_abs}" pos)
        if(pos EQUAL 0)
            set(inside TRUE)
            break()
        endif()
    endforeach()
    set(${out_var} ${inside} PARENT_SCOPE)
endfunction()

# Resolve with gp_resolve_item (searches SEARCH_DIRS first), then copy only if under SEARCH_DIRS
function(copy_dependencies target_file)
    # Pass SEARCH_DIRS so GetPrerequisites can resolve non-system DLLs (avoids bare "libusb-1.0.dll")
    get_prerequisites("${target_file}" PREREQS 1 1 "" "${SEARCH_DIRS}")

    foreach(PREREQ ${PREREQS})
        set(resolved_item "")
        get_filename_component(_prereq_name "${PREREQ}" NAME)
        # Prefer explicit search dirs first (no warning from gp_resolve_item)
        foreach(d IN LISTS SEARCH_DIRS)
            if(EXISTS "${d}/${_prereq_name}")
                get_filename_component(resolved_item "${d}/${_prereq_name}" ABSOLUTE)
                break()
            endif()
        endforeach()
        if(NOT resolved_item)
            gp_resolve_item("${target_file}" "${PREREQ}" "" "${SEARCH_DIRS}" resolved_item)
        endif()
        if(resolved_item AND EXISTS "${resolved_item}")
            path_under_search_dirs("${resolved_item}" "${SEARCH_DIRS}" allowed)
            if(NOT allowed)
                continue()
            endif()
            get_filename_component(item_name "${resolved_item}" NAME)
            if(NOT EXISTS "${TARGET_DIR}/${item_name}")
                file(COPY "${resolved_item}" DESTINATION "${TARGET_DIR}")
                message(STATUS "Copied ${resolved_item} to ${TARGET_DIR}")
                copy_dependencies("${resolved_item}")
            endif()
        endif()
    endforeach()
endfunction()

copy_dependencies("${TARGET_FILE}")
