#
# Scan FOUNDATION_FACTORY_REGISTER in foundation sources and emit FactoryLink.cpp.
# See roadmap/plan-foundation-phase2.md — link anchors for libfoundation.a.
#

include_guard(GLOBAL)

#[=======================================================================[.rst:
foundation_generate_factory_link
-------------------------------

Generate ``FactoryLink.cpp`` with ``link::touch_<LinkId>()`` calls so the
application linker pulls factory registrar object files out of
``libfoundation.a``.

.. code-block:: cmake

   foundation_generate_factory_link(
       OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/generated/FactoryLink.cpp"
       SOURCES ${ALL_SRCS}
       EXCLUDE_LINK_IDS tools_os_serport_Serport
   )

Arguments:

``OUTPUT``
  Path of the generated ``.cpp`` file (required).

``SOURCES``
  List of source files to scan (typically ``ALL_SRCS`` after ``add_package``).

``EXCLUDE_LINK_IDS``
  Optional ``LinkId`` values (third argument of ``FOUNDATION_FACTORY_REGISTER``)
  to omit from the generated link list.
#]=======================================================================]

function(foundation_generate_factory_link)
    set(_options "")
    set(_oneValueArgs OUTPUT)
    set(_multiValueArgs SOURCES EXCLUDE_LINK_IDS)
    cmake_parse_arguments(_fgfl "${_options}" "${_oneValueArgs}" "${_multiValueArgs}" ${ARGN})

    if(NOT _fgfl_OUTPUT)
        message(FATAL_ERROR "foundation_generate_factory_link: OUTPUT is required")
    endif()
    if(NOT _fgfl_SOURCES)
        message(FATAL_ERROR "foundation_generate_factory_link: SOURCES is required")
    endif()

    set(_link_ids)
    foreach(_src IN LISTS _fgfl_SOURCES)
        if(NOT IS_ABSOLUTE "${_src}")
            set(_path "${CMAKE_SOURCE_DIR}/${_src}")
        else()
            set(_path "${_src}")
        endif()
        if(NOT EXISTS "${_path}")
            continue()
        endif()
        if(_path MATCHES "\\.(h|hpp)$")
            continue()
        endif()

        file(READ "${_path}" _content)
        string(REGEX REPLACE "[\r\n]+" " " _oneliner "${_content}")
        string(REGEX MATCHALL
               "FOUNDATION_FACTORY_REGISTER\\([^,]+,[ \"]+[^\"]+[ \"],[ ]*([A-Za-z0-9_]+)[ ]*\\)"
               _matches "${_oneliner}")
        foreach(_m IN LISTS _matches)
            string(REGEX REPLACE
                   "FOUNDATION_FACTORY_REGISTER\\([^,]+,[ \"]+[^\"]+[ \"],[ ]*([A-Za-z0-9_]+)[ ]*\\)"
                   "\\1" _id "${_m}")
            if(_id AND NOT _id IN_LIST _fgfl_EXCLUDE_LINK_IDS)
                list(APPEND _link_ids "${_id}")
            endif()
        endforeach()
    endforeach()

    list(REMOVE_DUPLICATES _link_ids)
    list(SORT _link_ids)

    set(_decls "")
    set(_calls "")
    foreach(_id IN LISTS _link_ids)
        string(APPEND _decls "void touch_${_id}();\n")
        string(APPEND _calls "    touch_${_id}();\n")
    endforeach()

    set(_out "${_fgfl_OUTPUT}")
    get_filename_component(_out_dir "${_out}" DIRECTORY)
    file(MAKE_DIRECTORY "${_out_dir}")

    set(_generated "// Generated by foundation_generate_factory_link() — do not edit.\n")
    string(APPEND _generated "// Reconfigure CMake after adding FOUNDATION_FACTORY_REGISTER in a .cpp.\n\n")
    string(APPEND _generated "#include \"tools/design/factory/LinkAll.hpp\"\n\n")
    string(APPEND _generated "namespace tools::design::factory::link\n{\n\n")
    string(APPEND _generated "${_decls}")
    string(APPEND _generated "\n} // namespace tools::design::factory::link\n\n")
    string(APPEND _generated "namespace tools::design::factory\n{\n\n")
    string(APPEND _generated "void foundationFactoryLinkAll()\n{\n")
    string(APPEND _generated "    using namespace link;\n")
    string(APPEND _generated "${_calls}")
    string(APPEND _generated "}\n\n")
    string(APPEND _generated "} // namespace tools::design::factory\n")

    file(WRITE "${_out}" "${_generated}")
    message(STATUS "foundation_generate_factory_link: ${CMAKE_CURRENT_SOURCE_DIR} -> ${_out} (${_link_ids})")
endfunction()
